import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0Noiiqm202TtPahFjVe-0dnhvQVNSf4W2Fw&s" type="image/png" sizes="32x32" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
